models:
  - model: meta-llama/Meta-Llama-3-8B
    # No parameters necessary for base model
  - model: meta-llama/Meta-Llama-3-8B-Instruct
    parameters:
      density: 0.53
      weight: 0.6
  - model: aaditya/Llama3-OpenBioLLM-8B
    parameters:
      density: 0.53
      weight: 0.4
merge_method: dare_ties
base_model: meta-llama/Meta-Llama-3-8B
parameters:
  int8_mask: true
dtype: bfloat16